#!/usr/bin/env bash
set -euo pipefail
source_root= dependency_prefix= stage_root= parallelism=
while [[ $# -gt 0 ]]; do case "$1" in --source-root) source_root=$2; shift 2;; --dependency-prefix) dependency_prefix=$2; shift 2;; --stage-root) stage_root=$2; shift 2;; --parallelism) parallelism=$2; shift 2;; *) exit 64;; esac; done
[[ -n "$source_root" && -n "$dependency_prefix" && -n "$stage_root" && -n "$parallelism" && -n "${SOURCE_DATE_EPOCH:-}" ]]
marker="$stage_root/.ovayra-target"; [[ ! -e "$stage_root" || ( -f "$marker" && "$(<"$marker")" == x86_64-pc-windows-msvc ) ]] || exit 65
mkdir -p "$stage_root"/{provenance,LICENSES,sbom}; printf '%s\n' x86_64-pc-windows-msvc > "$marker"
cd "$source_root/libvpx"; ./configure --target=x86_64-win64-vs17 --prefix="$dependency_prefix" --disable-examples --disable-tools; make -j"$parallelism"; make test; make install
cd "$source_root/opus"; ./configure --host=x86_64-w64-mingw32 --prefix="$dependency_prefix" --disable-doc; make -j"$parallelism"; make check; make install
cd "$source_root/nv-codec-headers"; make PREFIX="$dependency_prefix" install
cd "$source_root/ffmpeg"; args=(--prefix="$stage_root" --toolchain=msvc --target-os=win32 --arch=x86_64 --disable-autodetect --disable-debug --disable-doc --disable-ffplay --disable-network --enable-ffmpeg --enable-ffprobe --enable-libopus --enable-libvpx --enable-version3 --disable-gpl --disable-nonfree --enable-d3d11va --enable-mediafoundation --enable-nvenc --enable-nvdec --extra-cflags="-I$dependency_prefix/include" --extra-ldflags="-L$dependency_prefix/lib"); printf 'configuration: '; printf '%q ' "${args[@]}"; printf '\n' > "$stage_root/provenance/buildconf.txt"; ./configure "${args[@]}"; make -j"$parallelism"; targets=$(make fate-list | grep -E '^fate-(lavf-matroska|vp9|opus)' | head -n 3 || true); [[ -n "$targets" ]]; set -- $targets; make "$@"; make install
cp "$source_root"/{ffmpeg-8.1.2.tar.xz,ffmpeg-8.1.2.tar.xz.asc,libvpx-source.tar.zst,opus-source.tar.zst,nv-codec-headers-source.tar.zst,ffmpeg-signature-attestation.json} "$stage_root/provenance/"; cp "$(dirname "$0")/../packaging/ffmpeg.lock" "$stage_root/provenance/ffmpeg.lock"; diff -ruN "$source_root/ffmpeg.pristine" "$source_root/ffmpeg" > "$stage_root/provenance/changes.diff" || [[ $? -eq 1 ]]; cp "$source_root/ffmpeg/COPYING.LGPLv2.1" "$stage_root/LICENSES/FFmpeg-LGPL-2.1-or-later.txt"; cp "$source_root/libvpx/LICENSE" "$stage_root/LICENSES/libvpx-BSD-3-Clause.txt"; cp "$source_root/opus/COPYING" "$stage_root/LICENSES/Opus-BSD-3-Clause.txt"; cp "$source_root/nv-codec-headers/LICENSE" "$stage_root/LICENSES/nv-codec-headers-MIT.txt"; cp "$(dirname "$0")/../packaging/NOTICE.txt" "$stage_root/NOTICE.txt"; ff=$(sha256sum "$stage_root/provenance/ffmpeg-8.1.2.tar.xz"|awk '{print $1}'); vx=$(sha256sum "$stage_root/provenance/libvpx-source.tar.zst"|awk '{print $1}'); op=$(sha256sum "$stage_root/provenance/opus-source.tar.zst"|awk '{print $1}'); printf '{"bomFormat":"CycloneDX","specVersion":"1.5","components":[{"name":"FFmpeg","version":"8.1.2","hashes":[{"alg":"SHA-256","content":"%s"}],"licenses":[{"license":{"id":"LGPL-2.1-or-later"}}]},{"name":"libvpx","version":"1.16.0","hashes":[{"alg":"SHA-256","content":"%s"}],"licenses":[{"license":{"id":"BSD-3-Clause"}}]},{"name":"opus","version":"1.6.1","hashes":[{"alg":"SHA-256","content":"%s"}],"licenses":[{"license":{"id":"BSD-3-Clause"}}]}]}' "$ff" "$vx" "$op" > "$stage_root/sbom/ffmpeg.cdx.json"; (cd "$stage_root" && find bin provenance LICENSES NOTICE.txt sbom -type f ! -name SHA256SUMS -print0 | sort -z | xargs -0 sha256sum > provenance/SHA256SUMS)
